######################################################################
# Automatically generated by qmake (2.01a) ne led 7 14:17:45 2018
######################################################################

TEMPLATE = app
TARGET = ECM3401
DEPENDPATH += .

INCLUDEPATH += .

LIBS += -L/usr/local/lib -lusb-1.0

# Input
HEADERS += daemon.h \
    connection.h
FORMS += mainwindow.ui
SOURCES += daemon.cpp main.cpp \
    connection.cpp


